### ISSUE TITLE
Similar project

### ISSUE THREAD

**Issue by omertuc** [alvaroaleman/static-kas#1]
Hey, I've been working on a similar project https://github.com/omertuc/o-must-external-reader

I've written it in Python rather than Go.

It's far from perfect and very buggy. My main goal was getting k9s to work somewhat ok, and i've come pretty far. You can view pods, containers, container logs (truncated due to k9s weirdness I've yet to figure out), yaml files.

I can't seem to get k9s to work at all with your fake API server, it wouldn't even connect. I wonder why. I also couldn't do `oc get pods -A` . 

Looking forward to seeing how you improve this, hopefully I could use your server with k9s some day. Or if you want, we can join efforts and work on my project (or the other way around) - but I'm not sure how much overlap there is in what we've done so far and what things mine can do and yours can't and vice versa.

Anyway just thought I should mention this

**Comment by alvaroaleman** [comment]
Hey @omertuc 

Thanks for your feedback! I'm using go here because that is what I am more familiar with and it also allows re-using code from the actual kubernetes apiserver, if needed :)

> I can't seem to get k9s to work at all with your fake API server, it wouldn't even connect. I wonder why. 

I looked a bit into that, it is using some endpoints that weren't implemented (/version, it does a self subject access review request..). It connects now, but doesn't show anything. I'll see if I can figure out what is missing.

> I also couldn't do oc get pods -A

That is because there wasn't support for listing namespaced resources across namespaces, i've added that in the meantime and it should work now.

> Looking forward to seeing how you improve this, hopefully I could use your server with k9s some day. Or if you want, we can join efforts and work on my project (or the other way around) - but I'm not sure how much overlap there is in what we've done so far and what things mine can do and yours can't and vice versa.

I'll likely keep working on this and extend it as needed. If you or anyone else for that matter sees things that can be improved, I am happy to look at a PR. Since this is super fresh there is a bit of a chance of conflicts right now though.

**Comment by alvaroaleman** [comment]
Ok, the remaining issue with k9s with a missing content type header in the ssar response, from the looks of it it is working now (but I've never used k9s before, so not sure). Can you check?

**Comment by omertuc** [comment]
That's awesome. Already works better than mine. Noticed 3 bugs, but at this point I'll close this ticket and open tickets for each one of them. Thank you so much. As someone who reads a lot of must-gathers getting a functional k9s would be an enormous boost of productivity
